[phases.setup]
cmds = [
    "python -m venv /opt/venv",
    "export PATH=/opt/venv/bin:$PATH"
]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "python app.py"